# Generated by Django 2.0.6 on 2018-06-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasts',
            options={'verbose_name_plural': 'Forecasts'},
        ),
    ]
