# Generated by Django 2.0.6 on 2018-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_auto_20180607_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecasts',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
