# Generated by Django 2.0.6 on 2018-06-10 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20180607_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecasts',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Forecasts'},
        ),
    ]
